### ISSUE TITLE
Expand Statement does not connect nodes initially

### ISSUE THREAD

**Issue by creisle** [bcgsc/pori_graphkb_client#47]
**Describe the bug**
Expanding a statement in graph view requires repeatedly clicking the button to get all elements and does not connect them until the end (see gif)

![Peek 2022-03-12 13-15](https://user-images.githubusercontent.com/4342641/158035349-a953a5f4-8ddf-4eab-bca5-d75059fa2d47.gif)

Should match the behaviour in production (see second gif)

![Peek 2022-03-12 13-21](https://user-images.githubusercontent.com/4342641/158035405-146589c2-ac6e-476d-a3c1-4a476dde714b.gif)

**Comment by areisle** [comment]
upon investigating I've found that this was caused by the babel changes when migrating to typescript. 
the behaviour of [this line](https://github.com/bcgsc/pori_graphkb_client/blob/bfb149767303a0ef1328cab7133b446a152f0e5a/src/views/GraphView/components/GraphComponent/GraphComponent.tsx#L228) changed due to [this](https://github.com/babel/babel/issues/6649)
